server:
  port: 8987

spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/PaymentDb?useSSL=false&serverTimezone=UTC
    username: root
    password: praise22
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL57InnoDBDialect
    hibernate:
      ddl-auto: update
  application:
    name: PAYMENT_SERVICE
  config:
    import: configserver:http://localhost:9296
